[package]
name = "aoc-2020"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.10"
thiserror = "1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[features]
defaults = []
# read_inputs = []